### ISSUE TITLE
use logging module over debug/warning hacks

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/INDXParse#19]
ref #16

**Comment by ajnelson** [comment]
I support using `logging.warning`.

For the sake of tracking logging messages through files, this module-level variable may do you some good:

    import logging
    import os
    _logger = logging.getLogger(os.path.basename(__file__))

**Comment by ajnelson** [comment]
(What a memory I have.  That's at least the third time I've put that snippet into some issue on this repository.)

**Comment by williballenthin** [comment]
closed in ee92814639278febb1acca174f849126be6f318e
