### ISSUE TITLE
don't silently use epoch timestamp for invalid timestamps

### ISSUE THREAD

**Issue by williballenthin** [williballenthin/INDXParse#20]
ref #16

**Comment by ajnelson** [comment]
My personal feeling is that invalid timestamps should always be presented from the earliest possible code level as `None`.  Higher code levels need to be honest about potentially processing invalid *or missing* data.

That's an easy absolutist position to take, though.  You mentioned some places where code would be complicated by null values - sorting and formatting.  What else would be negatively impacted?

If you need a sorting assistant in light of null data, SAS has a reasonable middle-ground: For sorting purposes, Null is treated as a numeric value less than negative infinity.  For `sorted()` calls, you can write a comparator function that swaps `-float("inf")` in for `None`.

**Comment by williballenthin** [comment]
closed in 67ef5e7753e5c7263553e32971c14e016c9f83cc
